version = 5.3.1
archive_dir = /etc/letsencrypt/archive/npm-1
cert = /etc/letsencrypt/live/npm-1/cert.pem
privkey = /etc/letsencrypt/live/npm-1/privkey.pem
chain = /etc/letsencrypt/live/npm-1/chain.pem
fullchain = /etc/letsencrypt/live/npm-1/fullchain.pem
[renewalparams]
account = 845e6c50139ca8963bcf3ee0f0d3e7cc
key_type = ecdsa
elliptic_curve = secp384r1
preferred_chain = ISRG Root X1
pref_challs = dns-01,
config_dir = /etc/letsencrypt
work_dir = /tmp/letsencrypt-lib
logs_dir = /data/logs
authenticator = dns-duckdns
dns_duckdns_credentials = /etc/letsencrypt/credentials/credentials-1
dns_duckdns_no_txt_restore = True
webroot_path = /data/letsencrypt-acme-challenge,
server = https://acme-v02.api.letsencrypt.org/directory
[[webroot_map]]
